# Generated by Django 4.0.3 on 2022-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0002_analisi_delete_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analisi1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=50)),
                ('tumori', models.CharField(max_length=50)),
                ('features', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='analisi',
            name='features',
        ),
        migrations.RemoveField(
            model_name='analisi',
            name='tumori',
        ),
        migrations.AddField(
            model_name='analisi',
            name='tumor',
            field=models.CharField(choices=[('none', 'Choice..'), ('ACC', 'ACC'), ('BLCA', 'BLCA'), ('BRCA', 'BRCA'), ('CESC', 'CESC'), ('CHOL', 'CHOL'), ('COAD', 'COAD'), ('DLBC', 'DLBC'), ('ESCA', 'ESCA'), ('GBM', 'GBM'), ('HNSC', 'HNSC'), ('KICH', 'KICH'), ('KIRC', 'KIRC')], default='Choice..', max_length=5),
        ),
        migrations.AlterField(
            model_name='analisi',
            name='gene',
            field=models.TextField(),
        ),
    ]
