# Generated by Django 4.0.3 on 2022-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0003_analisi1_remove_analisi_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisi',
            name='tumor',
            field=models.CharField(choices=[('none', 'Choice..'), ('ACC', 'ACC'), ('BLCA', 'BLCA'), ('BRCA', 'BRCA'), ('CESC', 'CESC'), ('CHOL', 'CHOL'), ('COAD', 'COAD'), ('DLBC', 'DLBC'), ('ESCA', 'ESCA'), ('GBM', 'GBM'), ('HNSC', 'HNSC'), ('KICH', 'KICH'), ('KIRC', 'KIRC')], default='Choice..', max_length=10),
        ),
    ]
