# Generated by Django 4.0.3 on 2022-04-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0004_alter_analisi_tumor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analisi1',
        ),
        migrations.AddField(
            model_name='analisi',
            name='feature',
            field=models.CharField(choices=[('none', 'Choice..'), ('gender', 'Gender'), ('age', 'Age'), ('radiation_therapy', 'Radiation therapy'), ('patient_status', 'Patient status'), ('diabetes', 'Diabetes'), ('tobacco_smoking_history', 'Tobacco smoking history'), ('menopause_status', 'Menopause status'), ('alcohol_history_documented', 'Alcohol history documented'), ('pathologic_stage', 'Pathologic stage')], default='Choice..', max_length=50),
        ),
        migrations.AlterField(
            model_name='analisi',
            name='gene',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='analisi',
            name='tumor',
            field=models.CharField(choices=[('none', 'Choice..'), ('ACC', 'ACC'), ('BLCA', 'BLCA'), ('BRCA', 'BRCA'), ('CESC', 'CESC'), ('CHOL', 'CHOL'), ('COAD', 'COAD'), ('DLBC', 'DLBC'), ('ESCA', 'ESCA'), ('GBM', 'GBM'), ('HNSC', 'HNSC'), ('KICH', 'KICH'), ('KIRC', 'KIRC'), ('KIRP', 'KIRP'), ('LGG', 'LGG'), ('LIHC', 'LIHC'), ('LUAD', 'LUAD'), ('LUSH', 'LUSH'), ('MESO', 'MESO'), ('OV', 'OV'), ('PAAD', 'PAAD'), ('PCPG', 'PCPG'), ('PRAD', 'PRAD'), ('READ', 'READ'), ('SARC', 'SARC'), ('SKCM', 'SKCM'), ('STAD', 'STAD'), ('TGCT', 'TGCT'), ('THCA', 'THCA'), ('THYM', 'THYM'), ('UCEC', 'UCEC'), ('UCS', 'UCS'), ('UVM', 'UVM')], default='Choice..', max_length=10),
        ),
    ]
