# Generated by Django 4.2.5 on 2024-09-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rolls", "0006_gene_analisi_mirna_alter_analisi_feature_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Gene",
            new_name="Names",
        ),
        migrations.AlterField(
            model_name="analisi",
            name="miRNA",
            field=models.CharField(max_length=20),
        ),
    ]
