# Generated by Django 5.1 on 2024-09-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0007_rename_gene_names_alter_analisi_mirna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Names',
        ),
    ]
