# Generated by Django 5.1 on 2024-09-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0008_gene_delete_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway', models.CharField(max_length=100)),
            ],
        ),
    ]
