# Generated by Django 5.1 on 2024-09-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolls', '0011_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene_symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_symbol', models.CharField(max_length=100)),
            ],
        ),
    ]
